branch-defaults:
  default:
    environment: portal-env
    group_suffix: null
global:
  application_name: portal
  branch: null
  default_ec2_keyname: comp680 csun
  default_platform: Python 2.7
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
